<?php
try {
  $cnx = new PDO('mysql:host=localhost;dbname=gencongo','root','',
  array(PDO::MYSQL_ATTR_INIT_COMMAND => "SET NAMES utf8"));
}
catch(Exception $e) {
  die($e->getMessage());
}

$reponses = $cnx->query('SELECT * FROM animal');
$nb=$reponses->rowCount();

?>
<!DOCTYPE html>
	<html>
		<head>
			<meta charset="utf-8"/>
			<title>Détail sur l'espèce choisi </title>
			<style>
				table{
					border-collapse:collapse;
				}
			</style>
		</head>
		<body>
			<center>
			<a href="controleur/formulaire_ajout.php">ajout</a><br><br>
			<table border>
				<thead>
					<tr>
						<th>id</th>
						<th>Espece</th>
						<th>Nom de l'animal</th>
						<th>Sexe</th>
						<th>date de naissance</th>
						<th>Commentaire</th>
						<th>Action</th>
					</tr>
				<thead>
				<tbody>
				
					<?php 
					while($animal=$reponses->fetch()){
						echo "<tr>";
							echo "<td>";
								echo $animal['id'];
							echo "</td>";
							
							echo "<td>";
								echo $animal['espece'];
							echo "</td>";
							
							echo "<td>";
								echo $animal['nom'];
							echo "</td>";
							
							echo "<td>";
								echo $animal['sexe'];
							echo "</td>";
							
							echo "<td>";
								echo $animal['date_naissance'];
							echo "</td>";
							
							echo "<td>";
								echo $animal['commentaires'];
							echo "</td>";
							echo "<td>";
								echo '<a href="controleur/formulaire_modif.php?idAnimal='.$animal['id'].'">modif</a> &nbsp &nbsp 
									<a href="model/formulaire_supp.php?idAnimal='.$animal['id'].'">suppr</a>' ;
							echo "</td>";
						echo "</tr>";
					}
					?>
					<tfoot>
						<tr>
							<th colspan="5">total résult <?php echo "Nombre d'enregistrement : ".$nb; ?></th>
						</tr>
					</tfoot>
				</tbody>
			</table>
			
			</center>
		</body>
	</html>